import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Interstellar Network sidebar - manually assign files here
  // To add a new file: add its ID (filename without .md/.mdx extension) to this array
  // Example: 'my-file' for docs/my-file.md, or 'folder/my-file' for docs/folder/my-file.md
  networkSidebar: [
    'interstellar-network',
    {
      type: 'category',
      label: 'Authentication',
      link: {
        type: 'generated-index',
        description: 'Explore Interstellar\'s breakthrough authentication technology ✨',
      },
      items: [
        'authentication/pohi',
        'authentication/dynamic-visual-cryptography',
        'authentication/visual-simulation',
        'authentication/garbled-circuits',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        description: 'Explore Interstellar\'s architecture and technology stack ✨',
      },
      items: [
        'architecture/mobile-devices',
        'architecture/interstellar-blockchain',
        'architecture/technology-stack',
      ],
    },
  ],

  // Mobile SDK sidebar - manually assign files here
  // To add a new file: add its ID (filename without .md/.mdx extension) to this array
  sdkSidebar: [
    'mobile-sdk',
    {
      type: 'category',
      label: 'Features',
            link: {
        type: 'generated-index',
        description: 'Explore Interstellar\'s unique mobile SDK features ✨',
      },
      items: [
        'features/instant-wallet-creation',
        'features/one-tap-wallet-backup',
        'features/proof-of-human-validation',
        'features/sybil-resistance',
      ],
    },
    // Add more files here as needed, e.g.:
    // 'new-file',
    // 'another-file',
  ],

  // Original autogenerated sidebar (preserved - can be restored if needed)
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Original manual sidebar example (preserved)
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
